apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-workernew02
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: isc-fds-worker02 # target worker
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
